#!/usr/bin/env bash
# Build Armbian Ubuntu 26.04 (resolute) for Orange Pi 5 Pro. Run this AFTER
# booting the 24.04 image produced by 01-build-noble.sh, NOT directly on stock
# Orange Pi vendor Ubuntu 22.04 — that kernel lacks CONFIG_BINFMT_MISC and the
# rust-coreutils chroot panic workaround can't deploy qemu-user-static.
#
# Usage:
#   ./02-build-resolute.sh                  # minimal CLI image (default)
#   ./02-build-resolute.sh --desktop        # with KDE Plasma + SDDM
#   DESKTOP=yes ./02-build-resolute.sh      # same via env var
#   BRANCH=vendor ./02-build-resolute.sh    # use Rockchip BSP (no GPU accel — see issue #1)
#
# Defaults to BRANCH=current (mainline ~6.18 kernel) for working GPU
# acceleration via panthor + Mesa panvk. Set BRANCH=vendor in the environment
# only if you specifically need the Rockchip BSP (NPU access, vendor MPP video
# accel) — the result will be Plasma-usable but software-rendered only.
#
# A small patch (apply-uutils-shim.sh) swaps rust-coreutils symlinks for a
# qemu-user-static shim during the build and restores them before image
# creation. The final image ships clean uutils.
#
# Output: ~/armbian-build/framework/output/images/Armbian-*_resolute_*.img.xz

set -euo pipefail

DESKTOP="${DESKTOP:-no}"
BRANCH="${BRANCH:-current}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --desktop)    DESKTOP=yes; shift ;;
        --no-desktop) DESKTOP=no; shift ;;
        --branch=*)   BRANCH="${1#*=}"; shift ;;
        -h|--help)
            sed -n '2,16p' "$0" | sed 's/^# \?//'
            exit 0 ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

config_file="/boot/config-$(uname -r)"
if [[ -r "$config_file" ]] && grep -qE '^# CONFIG_BINFMT_MISC is not set' "$config_file"; then
    echo "ERROR: this kernel was built without CONFIG_BINFMT_MISC."
    echo "       The 26.04 build will fail. Boot Armbian noble first (Step 1 in README)."
    exit 1
fi

if ! mountpoint -q /proc/sys/fs/binfmt_misc/; then
    sudo modprobe binfmt_misc || true
fi

WORK="${WORK:-$HOME/armbian-build}"
mkdir -p "$WORK"
cd "$WORK"

if [[ ! -d framework ]]; then
    git clone --depth=1 https://github.com/armbian/build.git framework
fi

# Apply the rust-coreutils chroot-panic workaround (idempotent).
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_DIR="${WORK}/framework" "${script_dir}/apply-uutils-shim.sh"

# Note: Armbian's framework doesn't yet have resolute desktop environment
# configs (only bookworm / noble / jammy do as of May 2026), so --desktop
# can't go through BUILD_DESKTOP=yes (errors with "kde-plasma does not exist
# for resolute"). Instead we drop a userpatches/customize-image.sh that
# apt-installs kubuntu-desktop inside the chroot during build.
userpatches="${WORK}/framework/userpatches"
mkdir -p "$userpatches"
if [[ "$DESKTOP" == "yes" ]]; then
    echo ">>> Building image with KDE Plasma + HW video decode (MPP+rockchip-vaapi) baked in."
    echo ">>> Expect ~45-60 min and ~2 GB output."
    echo ">>> First boot lands at TTY: armbian-firstrun runs (set root password, create user),"
    echo ">>> then orangepi-setup auto-prompts for Plasma autostart / NVMe / etc."
    cat > "$userpatches/customize-image.sh" <<'CUSTOMIZE_EOF'
#!/bin/bash
# Auto-generated by 02-build-resolute.sh --desktop
set -e
export DEBIAN_FRONTEND=noninteractive

# --- 1. KDE Plasma + GPU diagnostic tools ---
# DO NOT pass --no-install-recommends here. kubuntu-desktop's recommends
# include xwayland / xserver-xorg-core that KWin-Wayland and any X11 desktop
# session need. Skipping recommends produced a half-broken image where SDDM
# greeter shows but no user session can compositor anything (blank screen).
apt-get update
apt-get install -y \
    kubuntu-desktop konsole mesa-utils vulkan-tools \
    xserver-xorg-core xwayland \
    git ca-certificates curl

# kubuntu-desktop's postinst flips default target to graphical, which makes
# SDDM grab tty1 before armbian-firstrun can prompt for root password / user
# creation. Force back to multi-user so first boot lands at a text console;
# orangepi-setup (auto-launched on first TTY login) flips it to graphical
# after the user has been created.
systemctl set-default multi-user.target

# --- 2. HW video decode stack (librockchip-mpp + rockchip-vaapi + libva-utils) ---
apt-get install -y --no-install-recommends \
    build-essential cmake meson ninja-build pkg-config \
    libdrm-dev libva-dev libva-drm2 libv4l-dev libudev-dev libssl-dev \
    nasm yasm

mkdir -p /tmp/hwvideo && cd /tmp/hwvideo

# librockchip-mpp
git clone --depth=1 https://github.com/rockchip-linux/mpp.git
( cd mpp && mkdir -p build && cd build && \
  cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=OFF .. && \
  make -j"$(nproc)" && \
  make install )
ldconfig

# woodyst/rockchip-vaapi
git clone --depth=1 https://github.com/woodyst/rockchip-vaapi.git
( cd rockchip-vaapi && \
  PKG_CONFIG_PATH=/usr/local/lib/pkgconfig make && \
  make install )

# libva-utils for vainfo
git clone --depth=1 https://github.com/intel/libva-utils.git
( cd libva-utils && \
  meson setup build --prefix=/usr/local && \
  ninja -C build install )
ldconfig

cd / && rm -rf /tmp/hwvideo

# Set LIBVA_DRIVER_NAME system-wide
mkdir -p /etc/profile.d
cat > /etc/profile.d/rockchip-vaapi.sh <<'PROF'
export LIBVA_DRIVER_NAME=rockchip
PROF

# --- 3. Bake in OrangePi5Pro repo + first-TTY-login auto-run hook ---
git clone --depth=1 https://github.com/mack42/OrangePi5Pro.git /usr/local/share/OrangePi5Pro
ln -sf /usr/local/share/OrangePi5Pro/03-setup.sh /usr/local/bin/orangepi-setup

# Auto-run orangepi-setup on the first interactive login on a real TTY (not
# SSH). Set the flag file FIRST so the hook never re-prompts on subsequent
# logins, even if the user Ctrl-C's mid-prompt or the script errors out. They
# can always re-invoke manually with: orangepi-setup
cat > /etc/profile.d/orangepi-firstrun.sh <<'PROF'
#!/bin/sh
# Auto-launch the OrangePi 5 Pro setup helper on first local TTY login.
case "$(tty 2>/dev/null)" in
    /dev/tty[0-9]*)
        if [ "$(id -u)" -ne 0 ] && [ ! -e "$HOME/.opi5pro-setup-done" ]; then
            touch "$HOME/.opi5pro-setup-done"
            echo "First-login setup helper. Re-run later with: orangepi-setup"
            echo
            /usr/local/bin/orangepi-setup || true
        fi
        ;;
esac
PROF
chmod +x /etc/profile.d/orangepi-firstrun.sh

apt-get clean
exit 0
CUSTOMIZE_EOF
    chmod +x "$userpatches/customize-image.sh"
else
    echo ">>> Building MINIMAL image (CLI). Expect ~8-15 min and ~300 MB output."
    rm -f "$userpatches/customize-image.sh"
fi

cd "${WORK}/framework"
exec ./compile.sh \
    BOARD=orangepi5pro \
    BRANCH="$BRANCH" \
    RELEASE=resolute \
    BUILD_MINIMAL=yes \
    BUILD_DESKTOP=no \
    KERNEL_CONFIGURE=no \
    COMPRESS_OUTPUTIMAGE=sha,xz \
    EXPERT=yes
